### ISSUE TITLE
Install with brew

### ISSUE THREAD

**Issue by axelburks** [PhotonQuantum/tmexclude#211]
Thanks for the tool, can you add support for install with homebrew?

**Comment by PhotonQuantum** [comment]
We had homebrew formula support before, but since this is a GUI app now, the old formula is not usable anymore. Unfortunately, I'm a bit busy these days, so I won't be able to work on a new cask for the time being. However, I'm open to suggestions and contributions on implementing homebrew support.

For anyone interested in helping out, the old formula and publish routine might be helpful:

https://github.com/PhotonQuantum/homebrew-tap
https://github.com/PhotonQuantum/tmexclude/blob/ebf6ecf9ddff45795736ddb8b91ff2e9f62f4aeb/formula.rb
https://github.com/PhotonQuantum/tmexclude/blob/ebf6ecf9ddff45795736ddb8b91ff2e9f62f4aeb/.github/workflows/release.yml

**Comment by aaronzs** [comment]
@PhotonQuantum I just made a PR (https://github.com/PhotonQuantum/homebrew-tap/pull/2) to your homebrew-tap.
